import 'package:flutter/material.dart';
import 'package:itax/utility/size_utils.dart';

import '../../utility/pref_utils.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  final _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  final Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  final Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.whiteA700,
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        labelMedium: TextStyle(
          color: appTheme.gray500,
          fontSize: 10.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: appTheme.gray800,
          fontSize: 18.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static const primaryColorScheme = ColorScheme.light();
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {


  // Blackf
  Color get black9003f => const Color(0X3F000000);

  // Blue
  Color get blue800 => const Color(0XFF2457C5);

  // Gray
  Color get gray500 => const Color(0XFF999999);
  Color get gray800 => const Color(0XFF434343);

  // LightBlueAAf
  Color get lightBlueA700Af => const Color(0XAF0075FF);

  // White
  Color get whiteA700 => const Color(0XFFFFFFFF);


  Color get black900 => const Color(0XFF000000);

  // Blue

  Color get blue80001 => const Color(0XFF2457C5);
  Color get blue800Af => const Color(0XAF2057CE);

  // BlueGray
  Color get blueGray100 => const Color(0XFFD5D5D5);
  Color get blueGray10001 => const Color(0XFFD9D9D9);

  // Cyan
  Color get cyan600 => const Color(0XFF00A9CE);

  // Gray
  Color get gray200 => const Color(0XFFEFEFEF);
  Color get gray40019 => const Color(0X19C1C1C1);
  Color get gray50 => const Color(0XFFFAFAFA);

  Color get gray50001 => const Color(0XFFA2A2A2);
  Color get gray50002 => const Color(0XFF979797);
  Color get gray50003 => const Color(0XFF999999);
  Color get gray700 => const Color(0XFF696969);
  Color get gray70001 => const Color(0XFF666666);
  Color get gray80001 => const Color(0XFF464646);
  Color get gray80002 => const Color(0XFF474747);
  Color get gray80003 => const Color(0XFF434343);
  Color get gray80004 => const Color(0XFF454545);
  Color get gray900 => const Color(0XFF272222);

  // Indigo
  Color get indigo400 => const Color(0XFF4979D1);
  Color get indigo40001 => const Color(0XFF4B7BD2);

  // LightBlueAAf

}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
