-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.concurrent.GuardedBy
-dontwarn com.google.errorprone.annotations.CanIgnoreReturnValue
-dontwarn com.google.errorprone.annotations.CheckReturnValue
-dontwarn com.google.errorprone.annotations.Immutable
-dontwarn com.google.errorprone.annotations.RestrictedApi
-keep public class com.itextpdf.**
-keep public class org.apache.**
-keep class org.apache.xml.** { *; }
-keep class org.slf4j.** { *; }
-dontwarn org.apache.xml.**
-dontwarn org.slf4j.**